export const rules = {
  // Base rules
  curly: "error",
  yoda: "error",
  eqeqeq: ["error", "always", { null: "ignore" }],
  quotes: "off",
  indent: ["error", 4, { SwitchCase: 1 }],
  "no-empty": ["error", { allowEmptyCatch: true }],
  "new-cap": ["error", { properties: false }],
  "no-undef-init": "error",
  "no-trailing-spaces": "error",
  "eol-last": "error",
  "no-var": "error",
  "no-console": "off",
  "one-var": ["error", "never"],
  "no-self-compare": "error",
  "no-eval": "error",
  "quote-props": ["error", "as-needed"],
  "no-unneeded-ternary": "error",
  "dot-notation": "error",
  "no-extra-bind": "error",
  "new-parens": "error",
  "unicode-bom": "error",
  "linebreak-style": "error",
  "prefer-spread": "error",
  "prefer-const": ["error", { ignoreReadBeforeAssign: true }],
  "prefer-arrow-callback": ["error", { allowNamedFunctions: true }],
  "no-multiple-empty-lines": ["error", { max: 1, maxEOF: 0, maxBOF: 0 }],
  "spaced-comment": ["error", "always", { exceptions: ["/"], markers: ["/"], block: { balanced: true } }],
  "lines-between-class-members": ["error", "always", { exceptAfterSingleLine: true }],
  "no-multi-spaces": ["error", { ignoreEOLComments: true, exceptions: { PropertyAssignment: false } }],
  "array-callback-return": ["error", { checkForEach: true, allowImplicit: true }],
  "no-useless-escape": "off",
  "no-prototype-builtins": "off",
  "arrow-parens": "error",
  "arrow-spacing": "error",
  "no-useless-computed-key": "error",
  "rest-spread-spacing": "error",
  "no-useless-rename": "error",
  "template-curly-spacing": "error",
  "switch-colon-spacing": "error",
  "space-unary-ops": "error",
  "space-in-parens": "error",
  "space-before-blocks": "error",
  "semi-style": "error",
  "semi-spacing": "error",
  "padded-blocks": ["error", "never"],
  "no-whitespace-before-property": "error",
  "no-bitwise": "error",
  "key-spacing": "error",
  "no-return-assign": "error",
  "no-lone-blocks": "error",
  "func-name-matching": "error",
  "computed-property-spacing": "error",
  "comma-style": "error",
  "no-else-return": "error",
  "block-spacing": "error",
  "max-statements-per-line": "error",
  "no-nested-ternary": "error",
  "array-bracket-newline": ["error", "consistent"],
  "object-curly-newline": [
    "error",
    {
      ImportDeclaration: {
        multiline: true,
        minProperties: 3,
      },
      ExportDeclaration: "always",
    },
  ],
  "function-paren-newline": ["error", "consistent"],
  "array-element-newline": ["error", "consistent"],
  "object-property-newline": ["error", { allowAllPropertiesOnSameLine: true }],
  "function-call-argument-newline": ["error", "consistent"],
  "array-bracket-spacing": ["error", "never"],
  "operator-linebreak": ["error", "after"],
  "object-shorthand": "error",
  "object-curly-spacing": ["error", "always"],
  "padding-line-between-statements": [
    "error",
    { blankLine: "always", prev: "*", next: "return" },
    { blankLine: "always", prev: "*", next: "if" },
    { blankLine: "always", prev: "if", next: "*" },
    { blankLine: "always", prev: "*", next: "for" },
    { blankLine: "always", prev: "for", next: "*" },
    { blankLine: "always", prev: "*", next: "while" },
    { blankLine: "always", prev: "while", next: "*" },
    { blankLine: "always", prev: "*", next: "class" },
    { blankLine: "always", prev: "class", next: "*" },
    { blankLine: "always", prev: "*", next: "switch" },
    { blankLine: "always", prev: "switch", next: "*" },
  ],
  "max-len": [
    "error",
    {
      code: 120,
      ignoreTemplateLiterals: true,
      ignoreUrls: true,
      ignoreStrings: true,
      ignoreComments: true,
      ignorePattern: "^import |className|import\\(",
    },
  ],
  "prefer-rest-params": "off",
  "no-dupe-class-members": "off",
  "no-extra-semi": "off",
  "no-array-constructor": "off",
  "no-redeclare": "off",
  "space-infix-ops": "off",
  "no-unused-vars": "off",

  // node / promise
  "node/no-deprecated-api": "off",
  "node/no-unsupported-features/node-builtins": "off",
  "node/no-path-concat": "off",
  "promise/catch-or-return": ["error", { terminationMethod: ["catch", "finally"] }],

  // React
  "jsx-quotes": "error",
  "react-hooks/exhaustive-deps": "error",
  "react-hooks/rules-of-hooks": "error",
  "react/no-array-index-key": "warn",
  "react/no-deprecated": "off",
  "react/no-unknown-property": "off",
  "react/prop-types": "off",
  "react/jsx-no-target-blank": "off",
  "react/no-unsafe": ["error", { checkAliases: true }],
  "react/jsx-pascal-case": ["error", { allowAllCaps: true }],
  "react/jsx-no-bind": ["error", { ignoreDOMComponents: true, ignoreRefs: true, allowArrowFunctions: true }],
  "react/jsx-curly-brace-presence": ["error", { props: "never", children: "never" }],
  "react/jsx-boolean-value": ["error", "always"],
  "react/jsx-closing-bracket-location": "error",
  "react/jsx-closing-tag-location": "error",
  "react/jsx-equals-spacing": "error",
  "react/jsx-first-prop-new-line": "error",
  "react/jsx-indent": "error",
  "react/jsx-indent-props": "error",
  "react/self-closing-comp": "error",
  "react/void-dom-elements-no-children": "error",
  "react/jsx-no-constructed-context-values": "error",
  "react/jsx-key": ["error", { checkFragmentShorthand: true }],
  "react/jsx-curly-spacing": ["error", { when: "never", children: true }],
  "react/jsx-tag-spacing": ["error", { beforeClosing: "never" }],
  "react/jsx-max-props-per-line": ["error", { maximum: 1 }],
  "react/jsx-wrap-multilines": [
    "error",
    {
      declaration: "parens-new-line",
      assignment: "parens-new-line",
      return: "parens-new-line",
      arrow: "parens-new-line",
      condition: "parens-new-line",
      logical: "parens-new-line",
      prop: "parens-new-line",
    },
  ],
  "react/react-in-jsx-scope": 0,
  "react/jsx-uses-react": 0,
  "react/no-render-return-value": "error",

  // @stylistic
  "@stylistic/keyword-spacing": "error",
  "@stylistic/comma-spacing": "error",
  "@stylistic/brace-style": "error",
  "@stylistic/func-call-spacing": "error",
  "@stylistic/no-extra-parens": ["error", "functions"],
  "@stylistic/quotes": ["error", "single", { avoidEscape: true }],
  "@stylistic/semi": "error",
  "@stylistic/no-extra-semi": "error",
  "@stylistic/space-before-function-paren": ["error", { anonymous: "never", named: "never", asyncArrow: "always" }],
  "@stylistic/space-infix-ops": "error",
  "@stylistic/comma-dangle": ["error", "always-multiline"],
  "@stylistic/member-delimiter-style": ["error", { singleline: { delimiter: "comma", requireLast: false } }],
  "@stylistic/type-annotation-spacing": "error",

  // @typescript-eslint
  "@typescript-eslint/no-use-before-define": ["error", { variables: false }],
  "@typescript-eslint/no-unused-expressions": "error",
  "@typescript-eslint/prefer-for-of": "error",
  "@typescript-eslint/no-empty-function": ["error", { allow: ["methods", "arrowFunctions", "constructors"] }],
  "@typescript-eslint/no-array-constructor": "error",
  "@typescript-eslint/no-unused-vars": [
    "error",
    {
      vars: "local",
      argsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
      destructuredArrayIgnorePattern: "^_",
      varsIgnorePattern: "^_",
      ignoreRestSiblings: true,
    },
  ],
  "@typescript-eslint/naming-convention": [
    "error",
    {
      selector: "variable",
      format: ["camelCase", "PascalCase", "UPPER_CASE", "snake_case"],
      filter: { regex: "^_this$|^_$", match: false },
    },
    { selector: "parameter", format: ["camelCase", "PascalCase"], leadingUnderscore: "allow" },
    { selector: "typeLike", format: ["PascalCase"] },
    { selector: "enumMember", format: ["PascalCase"] },
    { selector: "interface", format: ["PascalCase"], prefix: ["I"] },
    { selector: "function", format: ["camelCase", "PascalCase"] },
    { selector: "method", format: ["camelCase"] },
    { selector: "accessor", format: ["camelCase"] },
  ],
  "@typescript-eslint/prefer-readonly": "off",
  "@typescript-eslint/no-unnecessary-type-arguments": "off",
  "@typescript-eslint/await-thenable": "off",
  "@typescript-eslint/require-array-sort-compare": "off",
  "@typescript-eslint/no-empty-interface": ["error", { allowSingleExtends: true }],
  "@typescript-eslint/prefer-function-type": "error",
  "@typescript-eslint/method-signature-style": ["error", "method"],
  "@typescript-eslint/array-type": "error",
  "@typescript-eslint/no-unnecessary-type-constraint": "error",
  "@typescript-eslint/adjacent-overload-signatures": "error",
  "@typescript-eslint/no-inferrable-types": ["error", { ignoreParameters: true, ignoreProperties: true }],
  "@typescript-eslint/no-empty-object-type": "error",
  "@typescript-eslint/no-wrapper-object-types": "error",
  "@typescript-eslint/consistent-type-assertions": "error",
  "@typescript-eslint/no-misused-new": "error",
  "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
  "@typescript-eslint/no-confusing-non-null-assertion": "error",
  "@typescript-eslint/prefer-literal-enum-member": "error",
  "@typescript-eslint/consistent-type-imports": ["error", { disallowTypeAnnotations: false }],
  "@typescript-eslint/consistent-type-exports": "off",

  // Disabled rules
  "@typescript-eslint/no-unsafe-argument": "off",
  "@typescript-eslint/no-unsafe-assignment": "off",
  "@typescript-eslint/no-unsafe-call": "off",
  "@typescript-eslint/no-unsafe-declaration-merging": "off",
  "@typescript-eslint/no-unsafe-enum-comparison": "off",
  "@typescript-eslint/no-unsafe-function-type": "off",
  "@typescript-eslint/no-unsafe-member-access": "off",
  "@typescript-eslint/no-unsafe-return": "off",
  "@typescript-eslint/no-unsafe-unary-minus": "off",
  "@typescript-eslint/unbound-method": "off",
  "@typescript-eslint/no-duplicate-enum-values": "off",
  "@typescript-eslint/no-require-imports": "off",
  "@typescript-eslint/no-var-requires": "off",
  "@typescript-eslint/no-unnecessary-type-assertion": "off",
  "@typescript-eslint/no-redundant-type-constituents": "off",
  "@typescript-eslint/no-misused-promises": "off",
  "@typescript-eslint/require-await": "off",
  "@typescript-eslint/no-floating-promises": "off",
  "@typescript-eslint/ban-ts-comment": "off",
  "@typescript-eslint/only-throw-error": "off",
  "@typescript-eslint/prefer-promise-reject-errors": "off",
  "@typescript-eslint/no-explicit-any": "off",
};


